import reframe as rfm
import reframe.utility.sanity as sn
#import CompareUtil as cu
parser = rfm.utility.import_module_from_file("Parser.py")
cu = rfm.utility.import_module_from_file("CompareUtil.py")
"""
Types of tags
--------------
compile: Make only tests
run: Make and run tests
unit: Tests that related to only a single function
aggregate: Tests for a complex function
slow: Tests requiring more than 30s of wall time
fast: Tests requiring less than 30s of wall time
cpu: Tests to be run on cpu only
gpu: Tests to be run on gpu only
"""

@rfm.simple_test
class MakeOnlyTest(rfm.CompileOnlyRegressionTest):
    descr = 'Test demonstrating use of CMake'
    valid_systems = ['*']
    valid_prog_environs = ['*']
    build_system = 'CMake'
    make_opts = ['all']
    builddir ='./build'
    sourcesdir = './src'
    tags = {"compile", "fast"}

    @run_before('compile')
    def set_compiler_flags(self):
        self.build_system.make_opts = self.make_opts
        ''' Set any compilation flag, configuration, environment variables, etc'''
        #NOTE: In most cases, setting the following attribues within a test should be avoided, 
        #it should be set within the config file. 
        #+ `build_system.cc` string to specify the C compiler
	    #+ `build_system.cflags` list of string to specify the C compiler flags
	    #+ `build_system.cxx` string to specify the C++ compiler
	    #+ `build_system.cxxflags` list of string to specify the C++ compiler flags
	    #+ `build_system.cppflags` list of string to specify the preprocessor flags
	    #+ `build_system.ldflags` list of string to specify the linker flags
	    #+ `build_system.nvcc` string to specify the CUDA compiler
        #+ `variables` a dictionary to set environment variables. e.g, 
        #  self.variables = {'DFT_EFE_LINKER': '"-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl"'}
        # Any special configuration that needs to be done externally can be done
        # using the prebuild_cmds attribute 
        # e.g., self.prebuild_cmds = ['./custom_configure -with-mylib']
        # Avoid using it as far as possible, in most cases one can invoke the
        # same configuration through CMake


    @run_before('sanity')
    def set_sanity_patterns(self):
        self.sanity_patterns = sn.assert_not_found(r'warning/i', self.stdout)


@rfm.simple_test
class NoExternalInputTest(rfm.RegressionTest):
    descr = 'Test demonstrating a Regression Test using CMake'
    valid_systems = ['*']
    valid_prog_environs = ['gnu']
    build_system = 'CMake'
    make_opts = ['all']
    #NOTE: Need to specify the name of the executable, as
    # ReFrame has no way of knowing that while building from CMake
    executable = './test'
    builddir ='./build'
    sourcesdir = './src'
    tags={"unit", "fast"}
    # By default ReFrame deletes all the output files generated by the test
    # In case you want to retain any of the files in the output folder of the
    # test, list them in keep_files attribute
    keep_files = ['out_test1']

    @run_before('compile')
    def set_compiler_flags(self):
        self.build_system.make_opts = self.make_opts
        ''' Set any compilation flag, configuration, environment variables, etc'''
        #NOTE: In most cases, setting the following attribues within a test should be avoided, 
        #it should be set within the config file. 
        #+ `build_system.cc` string to specify the C compiler
	    #+ `build_system.cflags` list of string to specify the C compiler flags
	    #+ `build_system.cxx` string to specify the C++ compiler
	    #+ `build_system.cxxflags` list of string to specify the C++ compiler flags
	    #+ `build_system.cppflags` list of string to specify the preprocessor flags
	    #+ `build_system.ldflags` list of string to specify the linker flags
	    #+ `build_system.nvcc` string to specify the CUDA compiler
        #+ `variables` a dictionary to set environment variables. e.g, 
        #  self.variables = {'DFT_EFE_LINKER': '"-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl"'}
        # Any special configuration that needs to be done externally can be done
        # using the prebuild_cmds attribute 
        # e.g., self.prebuild_cmds = ['./custom_configure -with-mylib']
        # Avoid using it as far as possible, in most cases one can invoke the
        # same configuration through CMake

    @sanity_function
    def validate_test(self):
        '''
        A user-defined function which decides whether the test passed or not as
        well as define an error message to display if the test fails.
        '''
        #NOTE: To make the tests portable, we do not hardcode any values or
        #error message in this file. Everything must be read from the output of
        #the test (either by catching the stdout or by reading from an output
        #file). The error message to display must be specified in this function
        #(or by invoking some other function from here). To integrate with
        #ReFrame's error handling and logging, we pass the boolean storing 
        #whether the test passed or not and the error message to ReFrame's
        # reframe.utility.sanity.assert_true(hasTestPassed, msg) function
        hasTestPassed = True
        msg = 'Failed for some reason'
        return sn.assert_true(hasTestPassed, msg=msg)

@rfm.simple_test
class ExternalInputTest(rfm.RegressionTest):
    descr = 'Test demonstrating a Regression Test using CMake'
    valid_systems = ['*']
    valid_prog_environs = ['gnu']
    build_system = 'CMake'
    make_opts = ['all']
    #NOTE: Need to specify the name of the executable, as
    # ReFrame has no way of knowing that while building from CMake
    executable = './test'
    # Provide the input through command line arguments
    # e.g., executable_opts = ['arg1', 'arg2'] where arg1, arg2,... are the command
    # line arguments
    executable_opts = ['InputFile']
    builddir ='./build'
    sourcesdir = './src'
    tags = {"aggregate", "slow"}
    # By default ReFrame deletes all the output files generated by the test
    # In case you want to retain any of the files in the output folder of the
    # test, list them in keep_files attribute
    keep_files = ['out_test1']

    @run_before('compile')
    def set_compiler_flags(self):
        self.build_system.make_opts = self.make_opts
        ''' Set any compilation flag, configuration, environment variables, etc'''
        #NOTE: In most cases, setting the following attribues within a test should be avoided, 
        #it should be set within the config file. 
        #+ `build_system.cc` string to specify the C compiler
	    #+ `build_system.cflags` list of string to specify the C compiler flags
	    #+ `build_system.cxx` string to specify the C++ compiler
	    #+ `build_system.cxxflags` list of string to specify the C++ compiler flags
	    #+ `build_system.cppflags` list of string to specify the preprocessor flags
	    #+ `build_system.ldflags` list of string to specify the linker flags
	    #+ `build_system.nvcc` string to specify the CUDA compiler
        #+ `variables` a dictionary to set environment variables. e.g, 
        #  self.variables = {'DFT_EFE_LINKER': '"-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl"'}
        # Any special configuration that needs to be done externally can be done
        # using the prebuild_cmds attribute 
        # e.g., self.prebuild_cmds = ['./custom_configure -with-mylib']
        # Avoid using it as far as possible, in most cases one can invoke the
        # same configuration through CMake

    @sanity_function
    def validate_test(self):
        '''
        A user-defined function which decides whether the test passed or not as
        well as define an error message to display if the test fails.
        '''
        #NOTE: To make the tests portable, we do not hardcode any values or
        #error message in this file. Everything must be read from the output of
        #the test (either by catching the stdout or by reading from an output
        #file). The error message to display must be specified in this function
        #(or by invoking some other function from here). To integrate with
        #ReFrame's error handling and logging, we pass the boolean storing 
        #whether the test passed or not and the error message to ReFrame's
        # reframe.utility.sanity.assert_true(hasTestPassed, msg) function
        hasTestPassed = True
        msg = 'Failed for some reason'
        bmfilename = "benchmark_test1"
        outfilename = "out_test1"
        bmParser = parser.Parser(bmfilename)
        outParser = parser.Parser(outfilename)
        bmVal = bmParser.extractKeyValues("Values")
        outVal = outParser.extractKeyValues("Values")
        hasTestPassed, msg = cu.Compare().cmp(bmVal[0], outVal[0])
        return sn.assert_true(hasTestPassed, msg=msg)

