var annotated_dup =
[
    [ "dftefe", "namespacedftefe.html", [
      [ "atoms", "namespacedftefe_1_1atoms.html", [
        [ "AtomSphericalDataXMLLocal", "namespacedftefe_1_1atoms_1_1AtomSphericalDataXMLLocal.html", [
          [ "XPathInfo", "structdftefe_1_1atoms_1_1AtomSphericalDataXMLLocal_1_1XPathInfo.html", "structdftefe_1_1atoms_1_1AtomSphericalDataXMLLocal_1_1XPathInfo" ]
        ] ],
        [ "AtomSphericalElectronicDataXMLLocal", "namespacedftefe_1_1atoms_1_1AtomSphericalElectronicDataXMLLocal.html", [
          [ "XPathInfo", "structdftefe_1_1atoms_1_1AtomSphericalElectronicDataXMLLocal_1_1XPathInfo.html", "structdftefe_1_1atoms_1_1AtomSphericalElectronicDataXMLLocal_1_1XPathInfo" ]
        ] ],
        [ "AtomSevereFunction", "classdftefe_1_1atoms_1_1AtomSevereFunction.html", "classdftefe_1_1atoms_1_1AtomSevereFunction" ],
        [ "OverlappingAtomIds", "classdftefe_1_1atoms_1_1OverlappingAtomIds.html", "classdftefe_1_1atoms_1_1OverlappingAtomIds" ],
        [ "SphericalData", "classdftefe_1_1atoms_1_1SphericalData.html", "classdftefe_1_1atoms_1_1SphericalData" ],
        [ "SphericalDataDefaults", "classdftefe_1_1atoms_1_1SphericalDataDefaults.html", "classdftefe_1_1atoms_1_1SphericalDataDefaults" ],
        [ "SphericalDataNumerical", "classdftefe_1_1atoms_1_1SphericalDataNumerical.html", "classdftefe_1_1atoms_1_1SphericalDataNumerical" ]
      ] ],
      [ "basis", "namespacedftefe_1_1basis.html", [
        [ "AtomIdsPartition", "classdftefe_1_1basis_1_1AtomIdsPartition.html", "classdftefe_1_1basis_1_1AtomIdsPartition" ],
        [ "BasisDataStorage", "classdftefe_1_1basis_1_1BasisDataStorage.html", "classdftefe_1_1basis_1_1BasisDataStorage" ],
        [ "BasisDofHandler", "classdftefe_1_1basis_1_1BasisDofHandler.html", "classdftefe_1_1basis_1_1BasisDofHandler" ],
        [ "BasisManager", "classdftefe_1_1basis_1_1BasisManager.html", "classdftefe_1_1basis_1_1BasisManager" ],
        [ "BasisOperations", "classdftefe_1_1basis_1_1BasisOperations.html", "classdftefe_1_1basis_1_1BasisOperations" ],
        [ "CellMappingBase", "classdftefe_1_1basis_1_1CellMappingBase.html", "classdftefe_1_1basis_1_1CellMappingBase" ],
        [ "CFEBasisDataStorageDealii", "classdftefe_1_1basis_1_1CFEBasisDataStorageDealii.html", "classdftefe_1_1basis_1_1CFEBasisDataStorageDealii" ],
        [ "CFEBasisDofHandlerDealii", "classdftefe_1_1basis_1_1CFEBasisDofHandlerDealii.html", "classdftefe_1_1basis_1_1CFEBasisDofHandlerDealii" ],
        [ "CFEConstraintsLocalDealii", "classdftefe_1_1basis_1_1CFEConstraintsLocalDealii.html", "classdftefe_1_1basis_1_1CFEConstraintsLocalDealii" ],
        [ "CFEOverlapInverseOperatorContext", "classdftefe_1_1basis_1_1CFEOverlapInverseOperatorContext.html", "classdftefe_1_1basis_1_1CFEOverlapInverseOperatorContext" ],
        [ "CFEOverlapOperatorContext", "classdftefe_1_1basis_1_1CFEOverlapOperatorContext.html", "classdftefe_1_1basis_1_1CFEOverlapOperatorContext" ],
        [ "ConstraintsInternal", "classdftefe_1_1basis_1_1ConstraintsInternal.html", "classdftefe_1_1basis_1_1ConstraintsInternal" ],
        [ "ConstraintsLocal", "classdftefe_1_1basis_1_1ConstraintsLocal.html", "classdftefe_1_1basis_1_1ConstraintsLocal" ],
        [ "EFEBasisDataStorage", "classdftefe_1_1basis_1_1EFEBasisDataStorage.html", "classdftefe_1_1basis_1_1EFEBasisDataStorage" ],
        [ "EFEBasisDataStorageDealii", "classdftefe_1_1basis_1_1EFEBasisDataStorageDealii.html", "classdftefe_1_1basis_1_1EFEBasisDataStorageDealii" ],
        [ "EFEBasisDofHandler", "classdftefe_1_1basis_1_1EFEBasisDofHandler.html", "classdftefe_1_1basis_1_1EFEBasisDofHandler" ],
        [ "EFEBasisDofHandlerDealii", "classdftefe_1_1basis_1_1EFEBasisDofHandlerDealii.html", "classdftefe_1_1basis_1_1EFEBasisDofHandlerDealii" ],
        [ "EFEConstraintsLocalDealii", "classdftefe_1_1basis_1_1EFEConstraintsLocalDealii.html", "classdftefe_1_1basis_1_1EFEConstraintsLocalDealii" ],
        [ "EFEOverlapInverseOperatorContext", "classdftefe_1_1basis_1_1EFEOverlapInverseOperatorContext.html", "classdftefe_1_1basis_1_1EFEOverlapInverseOperatorContext" ],
        [ "EFEOverlapOperatorContext", "classdftefe_1_1basis_1_1EFEOverlapOperatorContext.html", "classdftefe_1_1basis_1_1EFEOverlapOperatorContext" ],
        [ "EnrichmentClassicalInterfaceSpherical", "classdftefe_1_1basis_1_1EnrichmentClassicalInterfaceSpherical.html", "classdftefe_1_1basis_1_1EnrichmentClassicalInterfaceSpherical" ],
        [ "EnrichmentFunctionManagerAtomCenteredNumerical", "classdftefe_1_1basis_1_1EnrichmentFunctionManagerAtomCenteredNumerical.html", "classdftefe_1_1basis_1_1EnrichmentFunctionManagerAtomCenteredNumerical" ],
        [ "EnrichmentIdAttribute", "structdftefe_1_1basis_1_1EnrichmentIdAttribute.html", "structdftefe_1_1basis_1_1EnrichmentIdAttribute" ],
        [ "EnrichmentIdsPartition", "classdftefe_1_1basis_1_1EnrichmentIdsPartition.html", "classdftefe_1_1basis_1_1EnrichmentIdsPartition" ],
        [ "EnrichmentManager", "classdftefe_1_1basis_1_1EnrichmentManager.html", "classdftefe_1_1basis_1_1EnrichmentManager" ],
        [ "FEBasisDataStorage", "classdftefe_1_1basis_1_1FEBasisDataStorage.html", "classdftefe_1_1basis_1_1FEBasisDataStorage" ],
        [ "FEBasisDofHandler", "classdftefe_1_1basis_1_1FEBasisDofHandler.html", "classdftefe_1_1basis_1_1FEBasisDofHandler" ],
        [ "FEBasisManager", "classdftefe_1_1basis_1_1FEBasisManager.html", "classdftefe_1_1basis_1_1FEBasisManager" ],
        [ "FEBasisOperations", "classdftefe_1_1basis_1_1FEBasisOperations.html", "classdftefe_1_1basis_1_1FEBasisOperations" ],
        [ "FECellBase", "classdftefe_1_1basis_1_1FECellBase.html", "classdftefe_1_1basis_1_1FECellBase" ],
        [ "FECellDealii", "classdftefe_1_1basis_1_1FECellDealii.html", "classdftefe_1_1basis_1_1FECellDealii" ],
        [ "FECellWiseDataOperations", "classdftefe_1_1basis_1_1FECellWiseDataOperations.html", "classdftefe_1_1basis_1_1FECellWiseDataOperations" ],
        [ "Field", "classdftefe_1_1basis_1_1Field.html", "classdftefe_1_1basis_1_1Field" ],
        [ "L2ProjectionDefaults", "classdftefe_1_1basis_1_1L2ProjectionDefaults.html", "classdftefe_1_1basis_1_1L2ProjectionDefaults" ],
        [ "L2ProjectionLinearSolverFunction", "classdftefe_1_1basis_1_1L2ProjectionLinearSolverFunction.html", "classdftefe_1_1basis_1_1L2ProjectionLinearSolverFunction" ],
        [ "LinearCellMappingDealii", "classdftefe_1_1basis_1_1LinearCellMappingDealii.html", "classdftefe_1_1basis_1_1LinearCellMappingDealii" ],
        [ "ParentToChildCellsManagerBase", "classdftefe_1_1basis_1_1ParentToChildCellsManagerBase.html", "classdftefe_1_1basis_1_1ParentToChildCellsManagerBase" ],
        [ "ParentToChildCellsManagerDealii", "classdftefe_1_1basis_1_1ParentToChildCellsManagerDealii.html", "classdftefe_1_1basis_1_1ParentToChildCellsManagerDealii" ],
        [ "TriangulationBase", "classdftefe_1_1basis_1_1TriangulationBase.html", "classdftefe_1_1basis_1_1TriangulationBase" ],
        [ "TriangulationCellBase", "classdftefe_1_1basis_1_1TriangulationCellBase.html", "classdftefe_1_1basis_1_1TriangulationCellBase" ],
        [ "TriangulationCellDealii", "classdftefe_1_1basis_1_1TriangulationCellDealii.html", "classdftefe_1_1basis_1_1TriangulationCellDealii" ],
        [ "TriangulationDealiiParallel", "classdftefe_1_1basis_1_1TriangulationDealiiParallel.html", "classdftefe_1_1basis_1_1TriangulationDealiiParallel" ],
        [ "TriangulationDealiiSerial", "classdftefe_1_1basis_1_1TriangulationDealiiSerial.html", "classdftefe_1_1basis_1_1TriangulationDealiiSerial" ]
      ] ],
      [ "linearAlgebra", "namespacedftefe_1_1linearAlgebra.html", [
        [ "blasLapack", "namespacedftefe_1_1linearAlgebra_1_1blasLapack.html", [
          [ "blasLapackKernelsInternal", "namespacedftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal.html", [
            [ "ScalarProduct", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct.html", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct" ],
            [ "ScalarProduct< T1, T2, ScalarOp::Conj, ScalarOp::Conj >", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_9f7fe9f92c2e982edd941f400f0e9f01.html", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_9f7fe9f92c2e982edd941f400f0e9f01" ],
            [ "ScalarProduct< T1, T2, ScalarOp::Conj, ScalarOp::Identity >", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_fb168be88ad2507a1872b415dcc5248f.html", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_fb168be88ad2507a1872b415dcc5248f" ],
            [ "ScalarProduct< T1, T2, ScalarOp::Identity, ScalarOp::Conj >", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_fcf385721bd6542644c4bd709094cda0.html", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_fcf385721bd6542644c4bd709094cda0" ]
          ] ],
          [ "BlasQueueTypedef", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef.html", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef" ],
          [ "BlasQueueTypedef< dftefe::utils::MemorySpace::DEVICE >", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef_3_01dftefe_1_1utils_1_1MemorySpace_1_1DEVICE_01_4.html", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef_3_01dftefe_1_1utils_1_1MemorySpace_1_1DEVICE_01_4" ],
          [ "BlasQueueTypedef< dftefe::utils::MemorySpace::HOST >", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef_3_01dftefe_1_1utils_1_1MemorySpace_1_1HOST_01_4.html", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef_3_01dftefe_1_1utils_1_1MemorySpace_1_1HOST_01_4" ],
          [ "BlasQueueTypedef< dftefe::utils::MemorySpace::HOST_PINNED >", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef_3_01dftefe_1_1utils_1_1MemorySpace_1_1HOST__PINNED_01_4.html", "structdftefe_1_1linearAlgebra_1_1blasLapack_1_1BlasQueueTypedef_3_01dftefe_1_1utils_1_1MemorySpace_1_1HOST__PINNED_01_4" ],
          [ "KernelsOneValueType", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1KernelsOneValueType.html", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1KernelsOneValueType" ],
          [ "KernelsTwoValueTypes", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1KernelsTwoValueTypes.html", "classdftefe_1_1linearAlgebra_1_1blasLapack_1_1KernelsTwoValueTypes" ]
        ] ],
        [ "OperatorContextFE ", null, [
          [ "OperatorContext< ValueTypeOperator, ValueTypeOperand, memorySpace >", "classdftefe_1_1linearAlgebra_1_1OperatorContextFE_01_1_1OperatorContext_3_01ValueTypeOperator_0052fac58c39a07e8921677715bb495901.html", "classdftefe_1_1linearAlgebra_1_1OperatorContextFE_01_1_1OperatorContext_3_01ValueTypeOperator_0052fac58c39a07e8921677715bb495901" ]
        ] ],
        [ "ErrorMsg", "classdftefe_1_1linearAlgebra_1_1ErrorMsg.html", "classdftefe_1_1linearAlgebra_1_1ErrorMsg" ],
        [ "JacobiPreconditioner", "classdftefe_1_1linearAlgebra_1_1JacobiPreconditioner.html", "classdftefe_1_1linearAlgebra_1_1JacobiPreconditioner" ],
        [ "LinAlgOpContext", "classdftefe_1_1linearAlgebra_1_1LinAlgOpContext.html", "classdftefe_1_1linearAlgebra_1_1LinAlgOpContext" ],
        [ "LinearAlgebraProfiler", "classdftefe_1_1linearAlgebra_1_1LinearAlgebraProfiler.html", "classdftefe_1_1linearAlgebra_1_1LinearAlgebraProfiler" ],
        [ "LinearSolverDefaults", "classdftefe_1_1linearAlgebra_1_1LinearSolverDefaults.html", "classdftefe_1_1linearAlgebra_1_1LinearSolverDefaults" ],
        [ "LinearSolverImpl", "classdftefe_1_1linearAlgebra_1_1LinearSolverImpl.html", "classdftefe_1_1linearAlgebra_1_1LinearSolverImpl" ],
        [ "MultiVector", "classdftefe_1_1linearAlgebra_1_1MultiVector.html", "classdftefe_1_1linearAlgebra_1_1MultiVector" ],
        [ "OperatorContext", "classdftefe_1_1linearAlgebra_1_1OperatorContext.html", "classdftefe_1_1linearAlgebra_1_1OperatorContext" ],
        [ "Preconditioner", "classdftefe_1_1linearAlgebra_1_1Preconditioner.html", "classdftefe_1_1linearAlgebra_1_1Preconditioner" ],
        [ "PreconditionerJacobi", "classdftefe_1_1linearAlgebra_1_1PreconditionerJacobi.html", "classdftefe_1_1linearAlgebra_1_1PreconditionerJacobi" ],
        [ "PreconditionerNone", "classdftefe_1_1linearAlgebra_1_1PreconditionerNone.html", "classdftefe_1_1linearAlgebra_1_1PreconditionerNone" ],
        [ "PrintControlDefaults", "classdftefe_1_1linearAlgebra_1_1PrintControlDefaults.html", "classdftefe_1_1linearAlgebra_1_1PrintControlDefaults" ],
        [ "QueueManager", "classdftefe_1_1linearAlgebra_1_1QueueManager.html", "classdftefe_1_1linearAlgebra_1_1QueueManager" ],
        [ "Vector", "classdftefe_1_1linearAlgebra_1_1Vector.html", "classdftefe_1_1linearAlgebra_1_1Vector" ],
        [ "VectorAttributes", "classdftefe_1_1linearAlgebra_1_1VectorAttributes.html", "classdftefe_1_1linearAlgebra_1_1VectorAttributes" ]
      ] ],
      [ "physics", "namespacedftefe_1_1physics.html", [
        [ "LaplaceOperatorContextFE", "classdftefe_1_1physics_1_1LaplaceOperatorContextFE.html", "classdftefe_1_1physics_1_1LaplaceOperatorContextFE" ],
        [ "PoissonLinearSolverFunctionFE", "classdftefe_1_1physics_1_1PoissonLinearSolverFunctionFE.html", "classdftefe_1_1physics_1_1PoissonLinearSolverFunctionFE" ]
      ] ],
      [ "quadrature", "namespacedftefe_1_1quadrature.html", [
        [ "QuadraturePointAttributes", "classdftefe_1_1quadrature_1_1QuadraturePointAttributes.html", "classdftefe_1_1quadrature_1_1QuadraturePointAttributes" ],
        [ "QuadratureRule", "classdftefe_1_1quadrature_1_1QuadratureRule.html", "classdftefe_1_1quadrature_1_1QuadratureRule" ],
        [ "QuadratureRuleAdaptive", "classdftefe_1_1quadrature_1_1QuadratureRuleAdaptive.html", "classdftefe_1_1quadrature_1_1QuadratureRuleAdaptive" ],
        [ "QuadratureRuleAdaptiveDefaults", "classdftefe_1_1quadrature_1_1QuadratureRuleAdaptiveDefaults.html", "classdftefe_1_1quadrature_1_1QuadratureRuleAdaptiveDefaults" ],
        [ "QuadratureRuleAttributes", "classdftefe_1_1quadrature_1_1QuadratureRuleAttributes.html", "classdftefe_1_1quadrature_1_1QuadratureRuleAttributes" ],
        [ "QuadratureRuleAttributesDefaults", "classdftefe_1_1quadrature_1_1QuadratureRuleAttributesDefaults.html", "classdftefe_1_1quadrature_1_1QuadratureRuleAttributesDefaults" ],
        [ "QuadratureRuleContainer", "classdftefe_1_1quadrature_1_1QuadratureRuleContainer.html", "classdftefe_1_1quadrature_1_1QuadratureRuleContainer" ],
        [ "QuadratureRuleGauss", "classdftefe_1_1quadrature_1_1QuadratureRuleGauss.html", "classdftefe_1_1quadrature_1_1QuadratureRuleGauss" ],
        [ "QuadratureRuleGaussIterated", "classdftefe_1_1quadrature_1_1QuadratureRuleGaussIterated.html", "classdftefe_1_1quadrature_1_1QuadratureRuleGaussIterated" ],
        [ "QuadratureRuleGaussSubdividedDefaults", "classdftefe_1_1quadrature_1_1QuadratureRuleGaussSubdividedDefaults.html", "classdftefe_1_1quadrature_1_1QuadratureRuleGaussSubdividedDefaults" ],
        [ "QuadratureRuleGLL", "classdftefe_1_1quadrature_1_1QuadratureRuleGLL.html", "classdftefe_1_1quadrature_1_1QuadratureRuleGLL" ],
        [ "QuadratureValuesContainer", "classdftefe_1_1quadrature_1_1QuadratureValuesContainer.html", "classdftefe_1_1quadrature_1_1QuadratureValuesContainer" ]
      ] ],
      [ "utils", "namespacedftefe_1_1utils.html", [
        [ "mpi", "namespacedftefe_1_1utils_1_1mpi.html", [
          [ "MPICommunicatorP2P", "classdftefe_1_1utils_1_1mpi_1_1MPICommunicatorP2P.html", "classdftefe_1_1utils_1_1mpi_1_1MPICommunicatorP2P" ],
          [ "MPIErrorCodeHandler", "classdftefe_1_1utils_1_1mpi_1_1MPIErrorCodeHandler.html", "classdftefe_1_1utils_1_1mpi_1_1MPIErrorCodeHandler" ],
          [ "MPIPatternP2P", "classdftefe_1_1utils_1_1mpi_1_1MPIPatternP2P.html", "classdftefe_1_1utils_1_1mpi_1_1MPIPatternP2P" ],
          [ "MPIRequestersBase", "classdftefe_1_1utils_1_1mpi_1_1MPIRequestersBase.html", "classdftefe_1_1utils_1_1mpi_1_1MPIRequestersBase" ],
          [ "MPIRequestersNBX", "classdftefe_1_1utils_1_1mpi_1_1MPIRequestersNBX.html", "classdftefe_1_1utils_1_1mpi_1_1MPIRequestersNBX" ],
          [ "Types", "structdftefe_1_1utils_1_1mpi_1_1Types.html", "structdftefe_1_1utils_1_1mpi_1_1Types" ],
          [ "Types< char >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01char_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01char_01_4" ],
          [ "Types< double >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01double_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01double_01_4" ],
          [ "Types< float >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01float_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01float_01_4" ],
          [ "Types< int >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01int_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01int_01_4" ],
          [ "Types< long >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01long_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01long_01_4" ],
          [ "Types< long double >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01long_01double_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01long_01double_01_4" ],
          [ "Types< long long int >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01long_01long_01int_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01long_01long_01int_01_4" ],
          [ "Types< short >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01short_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01short_01_4" ],
          [ "Types< signed char >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01signed_01char_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01signed_01char_01_4" ],
          [ "Types< std::complex< double > >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01std_1_1complex_3_01double_01_4_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01std_1_1complex_3_01double_01_4_01_4" ],
          [ "Types< std::complex< float > >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01std_1_1complex_3_01float_01_4_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01std_1_1complex_3_01float_01_4_01_4" ],
          [ "Types< unsigned char >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01char_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01char_01_4" ],
          [ "Types< unsigned int >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01int_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01int_01_4" ],
          [ "Types< unsigned long >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01long_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01long_01_4" ],
          [ "Types< unsigned long long int >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01long_01long_01int_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01long_01long_01int_01_4" ],
          [ "Types< unsigned short >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01short_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01unsigned_01short_01_4" ],
          [ "Types< wchar_t >", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01wchar__t_01_4.html", "structdftefe_1_1utils_1_1mpi_1_1Types_3_01wchar__t_01_4" ]
        ] ],
        [ "splineInternal", "namespacedftefe_1_1utils_1_1splineInternal.html", [
          [ "band_matrix", "classdftefe_1_1utils_1_1splineInternal_1_1band__matrix.html", "classdftefe_1_1utils_1_1splineInternal_1_1band__matrix" ]
        ] ],
        [ "ConditionalOStream", "classdftefe_1_1utils_1_1ConditionalOStream.html", "classdftefe_1_1utils_1_1ConditionalOStream" ],
        [ "DiscontiguousDataOperations", "classdftefe_1_1utils_1_1DiscontiguousDataOperations.html", "classdftefe_1_1utils_1_1DiscontiguousDataOperations" ],
        [ "ExpModX", "classdftefe_1_1utils_1_1ExpModX.html", "classdftefe_1_1utils_1_1ExpModX" ],
        [ "Function", "classdftefe_1_1utils_1_1Function.html", "classdftefe_1_1utils_1_1Function" ],
        [ "LogModX", "classdftefe_1_1utils_1_1LogModX.html", "classdftefe_1_1utils_1_1LogModX" ],
        [ "MemoryManager", "classdftefe_1_1utils_1_1MemoryManager.html", "classdftefe_1_1utils_1_1MemoryManager" ],
        [ "MemoryManager< ValueType, MemorySpace::HOST >", "classdftefe_1_1utils_1_1MemoryManager_3_01ValueType_00_01MemorySpace_1_1HOST_01_4.html", "classdftefe_1_1utils_1_1MemoryManager_3_01ValueType_00_01MemorySpace_1_1HOST_01_4" ],
        [ "MemoryStorage", "classdftefe_1_1utils_1_1MemoryStorage.html", "classdftefe_1_1utils_1_1MemoryStorage" ],
        [ "MemoryTransfer", "classdftefe_1_1utils_1_1MemoryTransfer.html", "classdftefe_1_1utils_1_1MemoryTransfer" ],
        [ "MemoryTransfer< MemorySpace::HOST, MemorySpace::HOST >", "classdftefe_1_1utils_1_1MemoryTransfer_3_01MemorySpace_1_1HOST_00_01MemorySpace_1_1HOST_01_4.html", "classdftefe_1_1utils_1_1MemoryTransfer_3_01MemorySpace_1_1HOST_00_01MemorySpace_1_1HOST_01_4" ],
        [ "MPICommunicatorP2PKernels", "classdftefe_1_1utils_1_1MPICommunicatorP2PKernels.html", "classdftefe_1_1utils_1_1MPICommunicatorP2PKernels" ],
        [ "OptimizedIndexSet", "classdftefe_1_1utils_1_1OptimizedIndexSet.html", "classdftefe_1_1utils_1_1OptimizedIndexSet" ],
        [ "PeriodicTableManager", "classdftefe_1_1utils_1_1PeriodicTableManager.html", "classdftefe_1_1utils_1_1PeriodicTableManager" ],
        [ "PointImpl", "classdftefe_1_1utils_1_1PointImpl.html", "classdftefe_1_1utils_1_1PointImpl" ],
        [ "RandNumGen", "classdftefe_1_1utils_1_1RandNumGen.html", "classdftefe_1_1utils_1_1RandNumGen" ],
        [ "RandNumGen< double >", "classdftefe_1_1utils_1_1RandNumGen_3_01double_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01double_01_4" ],
        [ "RandNumGen< float >", "classdftefe_1_1utils_1_1RandNumGen_3_01float_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01float_01_4" ],
        [ "RandNumGen< int >", "classdftefe_1_1utils_1_1RandNumGen_3_01int_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01int_01_4" ],
        [ "RandNumGen< long >", "classdftefe_1_1utils_1_1RandNumGen_3_01long_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01long_01_4" ],
        [ "RandNumGen< long double >", "classdftefe_1_1utils_1_1RandNumGen_3_01long_01double_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01long_01double_01_4" ],
        [ "RandNumGen< long long >", "classdftefe_1_1utils_1_1RandNumGen_3_01long_01long_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01long_01long_01_4" ],
        [ "RandNumGen< short >", "classdftefe_1_1utils_1_1RandNumGen_3_01short_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01short_01_4" ],
        [ "RandNumGen< std::complex< double > >", "classdftefe_1_1utils_1_1RandNumGen_3_01std_1_1complex_3_01double_01_4_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01std_1_1complex_3_01double_01_4_01_4" ],
        [ "RandNumGen< std::complex< float > >", "classdftefe_1_1utils_1_1RandNumGen_3_01std_1_1complex_3_01float_01_4_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01std_1_1complex_3_01float_01_4_01_4" ],
        [ "RandNumGen< std::complex< long double > >", "classdftefe_1_1utils_1_1RandNumGen_3_01std_1_1complex_3_01long_01double_01_4_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01std_1_1complex_3_01long_01double_01_4_01_4" ],
        [ "RandNumGen< unsigned int >", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01int_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01int_01_4" ],
        [ "RandNumGen< unsigned long >", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01long_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01long_01_4" ],
        [ "RandNumGen< unsigned long long >", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01long_01long_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01long_01long_01_4" ],
        [ "RandNumGen< unsigned short >", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01short_01_4.html", "classdftefe_1_1utils_1_1RandNumGen_3_01unsigned_01short_01_4" ],
        [ "ScalarZeroFunctionReal", "classdftefe_1_1utils_1_1ScalarZeroFunctionReal.html", "classdftefe_1_1utils_1_1ScalarZeroFunctionReal" ],
        [ "Spline", "classdftefe_1_1utils_1_1Spline.html", "classdftefe_1_1utils_1_1Spline" ],
        [ "Types", "classdftefe_1_1utils_1_1Types.html", "classdftefe_1_1utils_1_1Types" ],
        [ "Types< char >", "classdftefe_1_1utils_1_1Types_3_01char_01_4.html", "classdftefe_1_1utils_1_1Types_3_01char_01_4" ],
        [ "Types< double >", "classdftefe_1_1utils_1_1Types_3_01double_01_4.html", "classdftefe_1_1utils_1_1Types_3_01double_01_4" ],
        [ "Types< float >", "classdftefe_1_1utils_1_1Types_3_01float_01_4.html", "classdftefe_1_1utils_1_1Types_3_01float_01_4" ],
        [ "Types< int >", "classdftefe_1_1utils_1_1Types_3_01int_01_4.html", "classdftefe_1_1utils_1_1Types_3_01int_01_4" ],
        [ "Types< long int >", "classdftefe_1_1utils_1_1Types_3_01long_01int_01_4.html", "classdftefe_1_1utils_1_1Types_3_01long_01int_01_4" ],
        [ "Types< short int >", "classdftefe_1_1utils_1_1Types_3_01short_01int_01_4.html", "classdftefe_1_1utils_1_1Types_3_01short_01int_01_4" ],
        [ "Types< std::complex< double > >", "classdftefe_1_1utils_1_1Types_3_01std_1_1complex_3_01double_01_4_01_4.html", "classdftefe_1_1utils_1_1Types_3_01std_1_1complex_3_01double_01_4_01_4" ],
        [ "Types< std::complex< float > >", "classdftefe_1_1utils_1_1Types_3_01std_1_1complex_3_01float_01_4_01_4.html", "classdftefe_1_1utils_1_1Types_3_01std_1_1complex_3_01float_01_4_01_4" ],
        [ "Types< std::string >", "classdftefe_1_1utils_1_1Types_3_01std_1_1string_01_4.html", "classdftefe_1_1utils_1_1Types_3_01std_1_1string_01_4" ],
        [ "Types< unsigned int >", "classdftefe_1_1utils_1_1Types_3_01unsigned_01int_01_4.html", "classdftefe_1_1utils_1_1Types_3_01unsigned_01int_01_4" ],
        [ "Types< unsigned long int >", "classdftefe_1_1utils_1_1Types_3_01unsigned_01long_01int_01_4.html", "classdftefe_1_1utils_1_1Types_3_01unsigned_01long_01int_01_4" ],
        [ "Types< unsigned short int >", "classdftefe_1_1utils_1_1Types_3_01unsigned_01short_01int_01_4.html", "classdftefe_1_1utils_1_1Types_3_01unsigned_01short_01int_01_4" ]
      ] ]
    ] ]
];