var searchData=
[
  ['cellmappingbase_0',['CellMappingBase',['../classdftefe_1_1basis_1_1_cell_mapping_base.html',1,'dftefe::basis']]],
  ['cellquadraturecontainer_1',['CellQuadratureContainer',['../classdftefe_1_1quadrature_1_1_cell_quadrature_container.html#aa32285363d530d832aeaf2139e893d3b',1,'dftefe::quadrature::CellQuadratureContainer::CellQuadratureContainer(std::shared_ptr&lt; const QuadratureRule &gt; quadratureRule, std::shared_ptr&lt; const basis::TriangulationBase &gt; triangulation, const basis::CellMappingBase &amp;cellMapping)'],['../classdftefe_1_1quadrature_1_1_cell_quadrature_container.html#aa784436c97ab0cf286eea0899736f639',1,'dftefe::quadrature::CellQuadratureContainer::CellQuadratureContainer(std::vector&lt; std::shared_ptr&lt; const QuadratureRule &gt; &gt; quadratureRuleVec, std::shared_ptr&lt; const basis::TriangulationBase &gt; triangulation, const basis::CellMappingBase &amp;cellMapping)'],['../classdftefe_1_1quadrature_1_1_cell_quadrature_container.html#ac3d3af26e3e5dbc80d422f18b3174ba4',1,'dftefe::quadrature::CellQuadratureContainer::CellQuadratureContainer(std::shared_ptr&lt; const QuadratureRule &gt; baseQuadratureRule, std::shared_ptr&lt; const basis::TriangulationBase &gt; triangulation, const basis::CellMappingBase &amp;cellMapping, basis::ParentToChildCellsManagerBase &amp;parentToChildCellsManager, std::vector&lt; std::shared_ptr&lt; const utils::ScalarSpatialFunctionReal &gt; &gt; functions, const std::vector&lt; double &gt; &amp;tolerances, const std::vector&lt; double &gt; &amp;integralThresholds, const double smallestCellVolume=1e-12, const unsigned int maxRecursion=100)'],['../classdftefe_1_1quadrature_1_1_cell_quadrature_container.html',1,'dftefe::quadrature::CellQuadratureContainer']]],
  ['conditionalostream_2',['ConditionalOStream',['../classdftefe_1_1utils_1_1_conditional_o_stream.html#a997679306b4fbf80605eb57cb7ea0f40',1,'dftefe::utils::ConditionalOStream::ConditionalOStream()'],['../classdftefe_1_1utils_1_1_conditional_o_stream.html',1,'dftefe::utils::ConditionalOStream']]],
  ['copy_3',['copy',['../classdftefe_1_1utils_1_1_memory_transfer.html#a7f0d9eed66c1e39ad68c80643f4b6ac0',1,'dftefe::utils::MemoryTransfer']]],
  ['copyfrom_4',['copyFrom',['../classdftefe_1_1utils_1_1_memory_storage.html#ae53237f8f422012c01111353a2feedce',1,'dftefe::utils::MemoryStorage::copyFrom(const MemoryStorage&lt; ValueType, memorySpaceSrc &gt; &amp;srcMemoryStorage)'],['../classdftefe_1_1utils_1_1_memory_storage.html#a4a49a9f627290a06b52d04e875ccb385',1,'dftefe::utils::MemoryStorage::copyFrom(MemoryStorage&lt; ValueType, memorySpaceSrc &gt; &amp;srcMemoryStorage, const size_type N, const size_type srcOffset, const size_type dstOffset)'],['../classdftefe_1_1utils_1_1_memory_storage.html#a894667edbf5c85aa988d3c1c235bcfc2',1,'dftefe::utils::MemoryStorage::copyFrom(const ValueType *src)'],['../classdftefe_1_1utils_1_1_memory_storage.html#adacc672f620df1c22be4705fd8e07484',1,'dftefe::utils::MemoryStorage::copyFrom(const ValueType *src, const size_type N, const size_type srcOffset, const size_type dstOffset)']]],
  ['copyto_5',['copyTo',['../classdftefe_1_1utils_1_1_memory_storage.html#afc501984e4ab70ce31da09a23f44911a',1,'dftefe::utils::MemoryStorage::copyTo(MemoryStorage&lt; ValueType, memorySpaceDst &gt; &amp;dstMemoryStorage) const'],['../classdftefe_1_1utils_1_1_memory_storage.html#a8c9c62e62c2fa3ce1c5ac0fee315972c',1,'dftefe::utils::MemoryStorage::copyTo(MemoryStorage&lt; ValueType, memorySpaceDst &gt; &amp;dstMemoryStorage, const size_type N, const size_type srcOffset, const size_type dstOffset) const'],['../classdftefe_1_1utils_1_1_memory_storage.html#abac4008165669560bd829ac66ff5e496',1,'dftefe::utils::MemoryStorage::copyTo(ValueType *dst) const'],['../classdftefe_1_1utils_1_1_memory_storage.html#ab7c59f5355ddf1d0358dcb56dabd0374',1,'dftefe::utils::MemoryStorage::copyTo(ValueType *dst, const size_type N, const size_type srcOffset, const size_type dstOffset) const']]]
];
