var searchData=
[
  ['parenttochildcellsmanagerdealii_0',['ParentToChildCellsManagerDealii',['../classdftefe_1_1basis_1_1ParentToChildCellsManagerDealii.html#a8f236ff3cab65a7ad0a8bb0c242a2dba',1,'dftefe::basis::ParentToChildCellsManagerDealii']]],
  ['periodictablemanager_1',['PeriodicTableManager',['../classdftefe_1_1utils_1_1PeriodicTableManager.html#a17e7adb590df24b5363a298f66a213cc',1,'dftefe::utils::PeriodicTableManager']]],
  ['plm_2',['Plm',['../namespacedftefe_1_1atoms_1_1SphericalHarmonicFunctionsInternal.html#a59b8d2f80b414cdd5c45e9bf8ae08bcc',1,'dftefe::atoms::SphericalHarmonicFunctionsInternal::Plm()'],['../namespacedftefe_1_1atoms.html#aee805f8eb58aff262e85ca4d08249c1c',1,'dftefe::atoms::Plm()'],['../classdftefe_1_1atoms_1_1SphericalHarmonicFunctions.html#a7b1a164b46658a955c70884273592dcd',1,'dftefe::atoms::SphericalHarmonicFunctions::Plm()']]],
  ['pointchargepotentialfunction_3',['PointChargePotentialFunction',['../classdftefe_1_1utils_1_1PointChargePotentialFunction.html#ad20026d1543d662dd3aa8d342953cf2b',1,'dftefe::utils::PointChargePotentialFunction::PointChargePotentialFunction(const utils::Point &amp;atomCoordinates, const double atomCharges)'],['../classdftefe_1_1utils_1_1PointChargePotentialFunction.html#a5f0cee2cc399e18a7571b5d284c98c48',1,'dftefe::utils::PointChargePotentialFunction::PointChargePotentialFunction(const std::vector&lt; utils::Point &gt; &amp;atomCoordinates, const std::vector&lt; double &gt; &amp;atomCharges)']]],
  ['pointimpl_4',['PointImpl',['../classdftefe_1_1utils_1_1PointImpl.html#acea11192eca7fc7bacf101536e197be6',1,'dftefe::utils::PointImpl::PointImpl(const std::vector&lt; T &gt; &amp;x)'],['../classdftefe_1_1utils_1_1PointImpl.html#ad0222ccb1e21af012005e68d5b5e58a5',1,'dftefe::utils::PointImpl::PointImpl(const T *x, size_type N)'],['../classdftefe_1_1utils_1_1PointImpl.html#a7af791440627f291c740c0c82201c775',1,'dftefe::utils::PointImpl::PointImpl(size_type N)'],['../classdftefe_1_1utils_1_1PointImpl.html#afd427f18053ab64cc2e3239647674c07',1,'dftefe::utils::PointImpl::PointImpl(size_type N, const_reference init)'],['../classdftefe_1_1utils_1_1PointImpl.html#a509611951fbba54d440cb3fd8c461d4e',1,'dftefe::utils::PointImpl::PointImpl(const PointImpl &amp;p)']]],
  ['poissonlinearsolverfunctionfe_5',['PoissonLinearSolverFunctionFE',['../classdftefe_1_1electrostatics_1_1PoissonLinearSolverFunctionFE.html#a5a07e257b6cb1acda2fbae46093bac0e',1,'dftefe::electrostatics::PoissonLinearSolverFunctionFE::PoissonLinearSolverFunctionFE(std::shared_ptr&lt; const basis::FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &gt; feBasisManagerField, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; feBasisDataStorageStiffnessMatrix, const std::map&lt; std::string, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; &gt; &amp;feBasisDataStorageRhs, const std::map&lt; std::string, const quadrature::QuadratureValuesContainer&lt; ValueType, memorySpace &gt; &amp; &gt; &amp;inpRhs, const linearAlgebra::PreconditionerType pcType, std::shared_ptr&lt; linearAlgebra::LinAlgOpContext&lt; memorySpace &gt; &gt; linAlgOpContext, const size_type maxCellBlock, const size_type maxFieldBlock)'],['../classdftefe_1_1electrostatics_1_1PoissonLinearSolverFunctionFE.html#a617e0f76790f1e591c7f4ff8f476d071',1,'dftefe::electrostatics::PoissonLinearSolverFunctionFE::PoissonLinearSolverFunctionFE(std::shared_ptr&lt; const basis::FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &gt; feBasisManagerField, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; feBasisDataStorageStiffnessMatrix, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; feBasisDataStorageRhs, const quadrature::QuadratureValuesContainer&lt; ValueType, memorySpace &gt; &amp;inpRhs, const linearAlgebra::PreconditionerType pcType, std::shared_ptr&lt; linearAlgebra::LinAlgOpContext&lt; memorySpace &gt; &gt; linAlgOpContext, const size_type maxCellBlock, const size_type maxFieldBlock)']]],
  ['poissonsolverdealiimatrixfreefe_6',['PoissonSolverDealiiMatrixFreeFE',['../classdftefe_1_1electrostatics_1_1PoissonSolverDealiiMatrixFreeFE.html#a5c1368cbc3016f9446c48062374f3c8c',1,'dftefe::electrostatics::PoissonSolverDealiiMatrixFreeFE::PoissonSolverDealiiMatrixFreeFE(std::shared_ptr&lt; const basis::FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &gt; feBasisManagerField, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; feBasisDataStorageStiffnessMatrix, const std::map&lt; std::string, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; &gt; &amp;feBasisDataStorageRhs, const std::map&lt; std::string, const quadrature::QuadratureValuesContainer&lt; ValueType, memorySpace &gt; &amp; &gt; &amp;inpRhs, const linearAlgebra::PreconditionerType pcType)'],['../classdftefe_1_1electrostatics_1_1PoissonSolverDealiiMatrixFreeFE.html#aee3dcd3c99893133d3716259f36a1ff5',1,'dftefe::electrostatics::PoissonSolverDealiiMatrixFreeFE::PoissonSolverDealiiMatrixFreeFE(std::shared_ptr&lt; const basis::FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &gt; feBasisManagerField, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; feBasisDataStorageStiffnessMatrix, std::shared_ptr&lt; const basis::FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &gt; feBasisDataStorageRhs, const quadrature::QuadratureValuesContainer&lt; ValueType, memorySpace &gt; &amp;inpRhs, const linearAlgebra::PreconditionerType pcType)']]],
  ['poplast_7',['popLast',['../classdftefe_1_1basis_1_1ParentToChildCellsManagerBase.html#adc1a0f6d7fa20486ba00e12fefb89924',1,'dftefe::basis::ParentToChildCellsManagerBase::popLast()'],['../classdftefe_1_1basis_1_1ParentToChildCellsManagerDealii.html#af0459ba59d26802792e369a41494cf88',1,'dftefe::basis::ParentToChildCellsManagerDealii::popLast()']]],
  ['popoldhistory_8',['popOldHistory',['../classdftefe_1_1ksdft_1_1MixingScheme.html#a71996d216bcd19259034988f16884752',1,'dftefe::ksdft::MixingScheme']]],
  ['potrf_9',['potrf',['../namespacedftefe_1_1linearAlgebra_1_1blasLapack.html#ae437fac8e4b66743d90128056668f15e',1,'dftefe::linearAlgebra::blasLapack::potrf(Uplo uplo, size_type n, ValueType *A, size_type lda, LinAlgOpContext&lt; dftefe::utils::MemorySpace::DEVICE &gt; &amp;context)'],['../namespacedftefe_1_1linearAlgebra_1_1blasLapack.html#a6b50a33edadbbfd3ffa5fabea860de10',1,'dftefe::linearAlgebra::blasLapack::potrf(Uplo uplo, size_type n, ValueType *A, size_type lda, LinAlgOpContext&lt; memorySpace &gt; &amp;context)']]],
  ['precondition_5fjacobi_10',['precondition_Jacobi',['../classdftefe_1_1electrostatics_1_1PoissonSolverDealiiMatrixFreeFE.html#acaec5f0a245bfeb226771d655a4e9c4d',1,'dftefe::electrostatics::PoissonSolverDealiiMatrixFreeFE']]],
  ['preconditionerjacobi_11',['PreconditionerJacobi',['../classdftefe_1_1linearAlgebra_1_1PreconditionerJacobi.html#aa4091c564b613546dd40e5497f20fdbf',1,'dftefe::linearAlgebra::PreconditionerJacobi']]],
  ['preconditionernone_12',['PreconditionerNone',['../classdftefe_1_1linearAlgebra_1_1PreconditionerNone.html#a4a4ef2925ae840b1c895fed65fd9cb7c',1,'dftefe::linearAlgebra::PreconditionerNone']]],
  ['print_13',['print',['../classdftefe_1_1utils_1_1Profiler.html#a0a60671dc77d5c62fce2427744118a3a',1,'dftefe::utils::Profiler']]],
  ['printaccumulatedwalltimedata_14',['printAccumulatedWallTimeData',['../classdftefe_1_1utils_1_1Timer.html#a8d57aa36b6812960f39300eaffd0c488',1,'dftefe::utils::Timer']]],
  ['printlastlapwalltimedata_15',['printLastLapWallTimeData',['../classdftefe_1_1utils_1_1Timer.html#af5d587ce00a10cb0216292c632c6185a',1,'dftefe::utils::Timer']]],
  ['pristineefeoverlapoperatorcontext_16',['PristineEFEOverlapOperatorContext',['../classdftefe_1_1basis_1_1PristineEFEOverlapOperatorContext.html#a5f49f8cba34f29f30b4a6f05461dcda2',1,'dftefe::basis::PristineEFEOverlapOperatorContext::PristineEFEOverlapOperatorContext(const FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &amp;feBasisManagerX, const FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &amp;feBasisManagerY, const FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &amp;cfeBasisDataStorage, const FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &amp;efeBasisDataStorage, const size_type maxCellBlock, const size_type maxFieldBlock)'],['../classdftefe_1_1basis_1_1PristineEFEOverlapOperatorContext.html#a69807721f1faac6867753922da46653d',1,'dftefe::basis::PristineEFEOverlapOperatorContext::PristineEFEOverlapOperatorContext(const FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &amp;feBasisManagerX, const FEBasisManager&lt; ValueTypeOperand, ValueTypeOperator, memorySpace, dim &gt; &amp;feBasisManagerY, const FEBasisDataStorage&lt; ValueTypeOperator, memorySpace &gt; &amp;feBasisDataStorage, const size_type maxCellBlock, const size_type maxFieldBlock)']]],
  ['probeandreceiveincomingmsg_17',['probeAndReceiveIncomingMsg',['../classdftefe_1_1utils_1_1mpi_1_1MPIRequestersNBX.html#a9378126f47c408a1455f041f9888f0dc',1,'dftefe::utils::mpi::MPIRequestersNBX']]],
  ['processsphericaldatafromxmlnodedata_18',['processSphericalDataFromXMLNodeData',['../namespacedftefe_1_1atoms_1_1AtomSphericalDataXMLLocal.html#a4b9025f3b87b3a770f085d652af657d6',1,'dftefe::atoms::AtomSphericalDataXMLLocal::processSphericalDataFromXMLNodeData()'],['../namespacedftefe_1_1atoms_1_1AtomSphericalElectronicDataXMLLocal.html#acf5cb0a812802d29a15697b4ede511a0',1,'dftefe::atoms::AtomSphericalElectronicDataXMLLocal::processSphericalDataFromXMLNodeData()']]],
  ['prod_19',['prod',['../classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct.html#aab4f59506e01f17561ea460e2f9a9564',1,'dftefe::linearAlgebra::blasLapack::blasLapackKernelsInternal::ScalarProduct::prod()'],['../classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_fcf385721bd6542644c4bd709094cda0.html#aa3dfa42e722fe9c6f97142a208feea4d',1,'dftefe::linearAlgebra::blasLapack::blasLapackKernelsInternal::ScalarProduct&lt; T1, T2, ScalarOp::Identity, ScalarOp::Conj &gt;::prod()'],['../classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_fb168be88ad2507a1872b415dcc5248f.html#a7b36887a781e57595145bfe396e42599',1,'dftefe::linearAlgebra::blasLapack::blasLapackKernelsInternal::ScalarProduct&lt; T1, T2, ScalarOp::Conj, ScalarOp::Identity &gt;::prod()'],['../classdftefe_1_1linearAlgebra_1_1blasLapack_1_1blasLapackKernelsInternal_1_1ScalarProduct_3_01T1_9f7fe9f92c2e982edd941f400f0e9f01.html#a0737b39489bfdf039585c7737df89fd2',1,'dftefe::linearAlgebra::blasLapack::blasLapackKernelsInternal::ScalarProduct&lt; T1, T2, ScalarOp::Conj, ScalarOp::Conj &gt;::prod()']]],
  ['profiler_20',['Profiler',['../classdftefe_1_1utils_1_1Profiler.html#a0505e27b5521aadb12bb940600c214b3',1,'dftefe::utils::Profiler::Profiler(const std::string &amp;profileName=&quot;&quot;)'],['../classdftefe_1_1utils_1_1Profiler.html#a049e3469a0a0588f936ce364b2bc0f99',1,'dftefe::utils::Profiler::Profiler(const mpi::MPIComm &amp;mpiComm, const std::string &amp;profileName=&quot;&quot;)'],['../classdftefe_1_1utils_1_1Profiler.html#abe661d7c6624c0f0dfec3c8853c72ac7',1,'dftefe::utils::Profiler::Profiler(const mpi::MPIComm &amp;mpiComm, const ConditionalOStream &amp;stream, const std::string &amp;profileName=&quot;&quot;)']]]
];
