#  Copyright (c) 2021.
#  The Regents of the University of Michigan and DFT-EFE developers.
#
#  This file is part of the DFT-EFE code.
#
#  DFT-EFE is free software: you can redistribute it and/or modify
#    it under the terms of the Lesser GNU General Public License as
#    published by the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#  DFT-EFE is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the Lesser GNU General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#    License at the top level of DFT-EFE distribution.  If not, see
#    <https://www.gnu.org/licenses/>.

import reframe as rfm
import reframe.utility.sanity as sn
from reframe.utility.sanity import evaluate
from reframe.core.backends import getlauncher
#import CompareUtil as cu
parser = rfm.utility.import_module_from_file("../Parser.py")
cu = rfm.utility.import_module_from_file("../CompareUtil.py")
ss = rfm.utility.import_module_from_file("../SetupSystems.py")

@rfm.simple_test
class StdOutTest(rfm.RegressionTest):
    descr = 'Regression Test using CMake and stdout'
    valid_systems = ['*']
    valid_prog_environs = ['*']
    build_system = 'CMake'
    make_opts = ['OperationHost']
    #NOTE: Need to specify the name of the executable, as
    # ReFrame has no way of knowing that while building from CMake
    executable = './OperationHost'
    builddir ='./build'
    sourcesdir = './src'
    # As a standard convention, we use 4 categories of tags that can help 
    # us run only tests matching certain tag(s). See the top of this file 
    # for the description on types. A user should populate the tagsDict with 
    # the appropriate values for each of the four keys: 'compileOrRun',
    # 'unitOrAggregate', 'arch', 'serialOrParallel'
    tagsDict = {'compileOrRun': 'compile', 'unitOrAggregate':
                'aggregate', 'slowOrFast': 'fast', 'arch': 'cpu',
                'serialOrParallel': 'serial'}
    tags = {x for x in tagsDict.values()}
    
    #Define valid_systems as a list of strings of the format
    #'system:partiion'. Over here, based on the 'arch' 
    #(i.e,,'cpu', 'gpu', or 'both'), we filter out
    #the system:partitions from a list named system_partition_list
    #in setupSystems.py. The convention is for 'arch'='cpu', we
    #select only those system:partitions that do not contain the string 'gpu' 
    #in it. Conversely, for 'arch'='gpu', only those system:partitions are
    #included which contains the string 'gpu'. For 'arch'='both', all the
    #system:partiions are selected.
    #NOTE: For any new systems:partition added to the config file, 
    # they must also be added to the system_partition_in setupSystems.py
    valid_systems = ss.getValidSystems(tagsDict['arch']) 
    valid_prog_environs = ['*']


    # By default ReFrame deletes all the output files generated by the test
    # In case you want to retain any of the files in the output folder of the
    # test, list them in keep_files attribute
    keep_files = ['out_test1']

    @run_before('compile')
    def set_compiler_flags(self):
        # set the make_opts as defined in the Constructor 
        self.build_system.make_opts = self.make_opts
        ''' Set any compilation flag, configuration, environment variables, etc'''
        #NOTE: In most cases, setting the following attribues within a test should be avoided, 
        #it should be set within the config file. 
        #+ `self.build_system.cc` string to specify the C compiler
	    #+ `self.build_system.cflags` list of string to specify the C compiler flags
	    #+ `self.build_system.cxx` string to specify the C++ compiler
	    #+ `self.build_system.cxxflags` list of string to specify the C++ compiler flags
	    #+ `self.build_system.cppflags` list of string to specify the preprocessor flags
	    #+ `self.build_system.ldflags` list of string to specify the linker flags
	    #+ `self.build_system.nvcc` string to specify the CUDA compiler
        #+ `self.variables` a dictionary to set environment variables. e.g, 
        #  self.variables = {'DFT_EFE_LINKER': '"-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl"'}
        # Any special configuration that needs to be done externally can be done
        # using the prebuild_cmds attribute 
        # e.g., self.prebuild_cmds = ['./custom_configure -with-mylib']
        # Avoid using it as far as possible, in most cases one can invoke the
        # same configuration through CMake
    
    @run_before('run')
    def set_launcher_and_resources(self):
        #By default in the config file the launcher for most systems:partitions
        #is set to srun or mpirun. However, for a serial job, we want to set it
        #to the local launcher (i.e., just ./exec)
        if "serial" in self.tags:
            self.job.launcher = getlauncher('local')()
        
        if "parallel" in self.tags:
            #For jobs launched through srun or mpirun, use the following
            #to set any launcher options
            #Example1: For srun -n 2 ./exec,
            # set the options as self.job.launcher.options = ['-n 2]
            #Example2: For binding cpu to cores 
            #self.job.launcher.options = ['--cpu-bind=cores']
            #self.job.launcher.options = ['launcher options to set']
            #By default it is kept blank (as defined below)
            self.job.launcher.options = ['']
   
        #In order to simplify the resource allocation procedure in a way that
        #is agnostic of the queueing system (Slurm, PBS, Torque, etc.), we use
        #the setResources() function defined in setupSystems.py. The
        #setResources() takes in the following paramters:
        #1. archTag: string that can be 'cpu', 'gpu', or 'both' (Default: 'both')
        #2. time_limit: string of the format "hrs:mins:secs" 
        #               (Default: "00:02:00")
        #3. num_nodes: integer for number of nodes to allocate (Default: 1)
        #4. num_tasks_per_node: integer for number of tasks to use per node 
        #                        (Default: 1)
        #5. mem_per_cpu: string of the format "<number>mb" or "<number>gb" for
        #                 the memory to allocate per cpu (Default: "2gb")
        #6. gpus_per_node: integer for number of gpus to allocate per node.
        #                  This is used only when the archTag='cpu' or 
        #                   archTag='both'. (Default: 1) 
        #Internally, setResources() function instantiates the 'resources' 
        #related placeholders defined in the cofig file. See REFRAME.md
        #for more details
        self.extra_resources = ss.setResources(self.tagsDict['arch'])

    @sanity_function
    def validate_test(self):
        '''
        A user-defined function which decides whether the test passed or not as
        well as define an error message to display if the test fails.
        '''
        #NOTE: To make the tests portable, we do not hardcode any values or
        #error message in this file. Everything must be read from the output of
        #the test (either by catching the stdout or by reading from an output
        #file). The error message to display must be specified in this function
        #(or by invoking some other function from here). To integrate with
        #ReFrame's error handling and logging, we pass the boolean storing 
        #whether the test passed or not and the error message to ReFrame's
        # reframe.utility.sanity.assert_true(hasTestPassed, msg) function
        hasTestPassed = True
        msg = 'Failed for some reason'
        bmfilename = "benchmark_test1"
        bmParser = parser.Parser.fromFilename(bmfilename)
        outParser = parser.Parser.fromFilename(evaluate(self.stdout))
        bmVal = bmParser.extractKeyValues("Values")
        outVal = outParser.extractKeyValues("Values")
        hasTestPassed, norm, msg = cu.Compare().cmp(bmVal[0], outVal[0])
        return sn.assert_true(hasTestPassed, msg=msg)
